export const PRODUCTS = [
  { id: "ajo", name: "Ajo", category: "Verdura", unit: "kg", price: 1200, image: "ajo.png" },
  { id: "banana", name: "Banana", category: "Fruta", unit: "kg", price: 950, image: "banana.png" },
  { id: "berenjena", name: "Berenjena", category: "Verdura", unit: "kg", price: 1100, image: "berenjena.png" },
  { id: "camote", name: "Camote", category: "Verdura", unit: "kg", price: 900, image: "camote.png" },
  { id: "choclo", name: "Choclo", category: "Verdura", unit: "unidad", price: 500, image: "choclo.png" },
  { id: "frutilla", name: "Frutilla", category: "Fruta", unit: "bandeja", price: 1600, image: "frutilla.png" },
  { id: "kiwi", name: "Kiwi", category: "Fruta", unit: "kg", price: 1400, image: "kiwi.png" },
  { id: "lechuga", name: "Lechuga", category: "Verdura", unit: "unidad", price: 700, image: "lechuga.png" },
  { id: "mandarina", name: "Mandarina", category: "Fruta", unit: "kg", price: 800, image: "mandarina.png" },
  { id: "manzana", name: "Manzana", category: "Fruta", unit: "kg", price: 1200, image: "manzana.png" },
  { id: "huevos", name: "Maple de Huevos", category: "Otros", unit: "maple (30u)", price: 2500, image: "maple_huevos.png" },
  { id: "melon", name: "Melón", category: "Fruta", unit: "unidad", price: 2000, image: "melon.png" },
  { id: "naranja", name: "Naranja", category: "Fruta", unit: "kg", price: 900, image: "naranja.png" },
  { id: "palta", name: "Palta", category: "Fruta", unit: "unidad", price: 700, image: "palta.png" },
  { id: "papa", name: "Papa", category: "Verdura", unit: "kg", price: 750, image: "papa.png" },
  { id: "pera", name: "Pera", category: "Fruta", unit: "kg", price: 950, image: "pera.png" },
  { id: "pimiento", name: "Pimiento", category: "Verdura", unit: "unidad", price: 600, image: "pimiento.png" },
  { id: "tomate", name: "Tomate", category: "Verdura", unit: "kg", price: 1000, image: "tomate.png" },
  { id: "uva", name: "Uva", category: "Fruta", unit: "kg", price: 1700, image: "uva.png" },
  { id: "zapallo", name: "Zapallo", category: "Verdura", unit: "kg", price: 850, image: "zapallo.png" },
];